# Generated by Django 4.0.3 on 2022-05-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teacher_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='student', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='teacher', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='studentName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='accounts.customer'),
        ),
    ]
