# Generated by Django 4.0.3 on 2022-05-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_status_teacher_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2022-05-23')),
                ('status', models.BooleanField(default=True)),
                ('score', models.FloatField(default=0.0)),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.customer')),
            ],
        ),
    ]
